User.destroy_all
Recipe.destroy_all
Ingredient.destroy_all


puts "Seeding users..."

User.create(username: "elizabeth", password: "elizabethiscool", password_confirmation: "elizabethiscool")

puts "Seeding recipes..."
# blt = Recipe.create(name: "blt", allergy_code: "vegan", ingredient_list: ["1 slice tomato", "2 slices bacon"], instructions: "put it together")
# salad = Recipe.create(name: "salad", allergy_code: "gf", ingredient_list: ["3 lettuce leaves", "1 quartered tomato"], instructions: "toss it together")

chinese_fried_rice = Recipe.create(name: "Chinese fried rice", allergy_code: "GF, VE, NF", ingredient_list: ["2 Tbsp sunflower oil", "1/2 cup broccoli - chopped", "1/8 cup onion - sliced", "1/2 cup carrot - julienned", "1/4 cup mirin", "1/4 cup bell pepper - diced", "1/4 cup asparagus - diced", "1 Tbsp GF soy sauce", "1/8 tsp chili flakes", "1/8 cup parsley - minced", "1/8 cup sesame oil", "1 1/2 cup rice - boiled"], instructions: "Put half of the sunflower oil in a large skillet on medium heat. Add broccoli, onion, carrot, and cook, stirring often, for a couple of minutes. Add mirin. Add bell pepper and asparagus. Season with soy sauce, chili flakes, and parsley. Cook until veggies are al dente. Remove from the pan, set aside. 
Put the rest of the sunflower oil and the sesame oil in the skillet over medium heat, add the rice, stir often until crispy. Add the veggies. Mix until combined. Serve hot.")
pasta_e_fagioli = Recipe.create(name: "Pasta e fagioli", allergy_code: "VE, NF", ingredient_list: ["2 Tbsp sunflower oil", "1/4 cup onion - diced", "1 garlic clove - minced", "1/4 cup celery - diced", "1/4 cup carrot - diced", "1 bay leaf", "1/8 cup parsley - minced", "1 tsp dried rosemary", "1/2 cup water", "1 cup (no salt added) canned diced tomatoes", "1 cup (no salt added) canned cannellini beans - drained", "1 1/2 cup kale - chopped", "1/4 tsp salt", "1/4 tsp black pepper", "1/2 cup elbow macaroni pasta", "1 1/2 cup vegetable broth"], instructions: "In a large non-stick pot, warm up half of the sunflower oil. Add the onion and the garlic and cook for 1 minute. Add the celery, the carrots, the bay leaves, the parsley, and the rosemary. Cook for 10 minutes, adding salt, pepper, and half of the water half way through. Add the tomatoes and cook for 5 minutes. Add the beans, the kale, the rest of the water, and the remaining vegetable oil. Let it simmer for 3 minutes. Add the pasta and the vegetable broth. Mix well. Cook uncovered on low heat stirring often (so the pasta doesn’t stick to the bottom of the pan), until the pasta is al dente; about 15 minutes. Adjust with salt and pepper. Serve hot.")
lentil_stew = Recipe.create(name: "Lentil stew with avocado salsa", allergy_code: "GF, VE, NF", ingredient_list: ["1/2 cup avocado - small diced", "1 Tbsp jalapeño - thinly sliced", "1/2 cup tomato - small diced", "1/4 cup onion - small diced", "1/8 cup cilantro - chopped", "1 Tbsp lime - juiced", "3/4 cup dry lentils", "1 garlic clove - minced", "1/4 tsp cumin", "3 cup water", "3/4 cup sweet potato - peeled, small diced", "1/2 cup tomato - diced", "1/2 cup celery - small diced", "1/4 cup bell pepper - diced", "1/2 tsp smoked paprika", "1/4 tsp salt, 1 1/2 cup rice - boiled, kept warm"], instructions: "Make the salsa: mix all the ingredients (from avocado to lime juice) together. Set aside in the cooler.
Make the stew: place the lentils, the garlic, the salt, and the cumin in a large pot; add the water. Cook over medium heat for 2 minutes. Add the sweet potatoes, cook for 10 minutes. Add the tomatoes, the celery, the bell pepper, and the smoked paprika and cook for 5 minutes. Adjust with salt. Serve hot with rice and avocado salsa on the side.")
polenta_with_veggies = Recipe.create(name: "Polenta with veggies stew", allergy_code: "GF, VE, NF", ingredient_list: ["4 1/2 cup water", "1/2 Tbsp salt", "1 Tbsp olive oil", "1 3/4 cup medium grain cornmeal flour", "2 Tbsp vegetable oil", "1/4 cup onion - diced", "1 garlic clove - minced", "1/2 cup eggplant - diced", "1/2 cup bell pepper - diced", "1/4 cup olives - pitted and chopped", "1/2 Tbsp smoked paprika", "1/2 tsp fennel seeds", "1/2 Tbsp dried basil", "1/2 tsp dried marjoram", "1/2 Tbsp dried parsley", "1/8 tsp chili flakes", "1 cup (no salt added) canned chickpeas - drained", "1 cup (no salt added) canned fire roasted tomatoes", "1/4 tsp salt"], instructions: "Make the polenta: bring the water to a boil in a big pot. Add the salt and the olive oil. Slowly pour the cornmeal into the water while continuously stirring it with a whisk to avoid the formation of lumps. When it starts boiling again, turn the heat to the lowest setting, cook for about 50 minutes, stirring every 5-10 minutes. Keep warm.
Meanwhile, make the stew: in a large pot, warm up the vegetable oil. Add the onion and the garlic, cook for 5 minutes on medium heat. Add the eggplant, cook for 5 minutes, stirring often and adding water to prevent it sticking to the bottom of the pot. Add the bell pepper, the olives, and all the spices and cook for 2 minutes. Add the chickpeas and the tomatoes and adjust with salt. Cook for 5 minutes. Serve hot alongside the polenta.")
ratatouille_quiche = Recipe.create(name: "Ratatouille quiche", allergy_code: "VE, NF", ingredient_list: ["1/4 cup vegetable oil", "1/4 tsp salt", "1 cup all purpose flour", "1/4 cup cold water", "1 1/2 Tbsp olive oil", "1/4 cup onion - diced", "1/4 cup zucchini - diced", "1/4 cup eggplant - diced", "1/4 cup mushrooms - diced", "1/4 cup green beans - diced", "1/4 cup bell pepper - diced", "1/2 cup (no salt added) canned diced tomatoes", "1/8 cup parsley - minced", "1/2 tsp dried thyme", "1/4 tsp salt", "1/4 tsp black pepper", "1 1/2 Tbsp coconut oil or vegan butter", "1 Tbsp flour", "1/2 cup rice milk", "1/8 tsp ground nutmeg", "1/4 tsp salt", "1/4 tsp black pepper"], instructions: "Make the dough: in a bowl mix all the ingredients (from vegetable oil to cold water) together, knead until just combined. Make a ball, cover it with plastic wrap and keep it in a cool place. Turn on the oven to 375 degrees F.
Make the ratatouille: in a large skillet, warm up the oil. Add the onion and cook for 2 minutes. Add the veggies and sauté them until al dente. Add the tomatoes and the herbs. Add salt and pepper to taste. Keep aside.
Make the vegan béchamel: in a medium pot melt the coconut oil over medium heat. Remove from heat, add the flour, whisk together until there are no more lumps. Add the milk slowly without stopping whisking until all is incorporated and there are no more lumps. Put the pot back on low heat, keep whisking to avoid the formation of lumps. Remove from heat when it starts getting dense. Add the nutmeg, and salt and pepper to taste. Keep aside.
Assemble the quiche: Roll out the dough. Oil an oven pan, place dough in it, dock the crust evenly with a fork. Pour in half of the ratatouille, level it out, pour in béchamel and level it out, cover with the rest of the ratatouille. 
Bake it until the crust is golden brown, about 35-45 minutes. Cut into slices and serve hot.")
veggies_and_tofu_curry = Recipe.create(name: "Veggies and tofu curry", allergy_code: "GF, VE, NF", ingredient_list: ["1 1/2 Tbsp suflower oil", "1/4 cup onion - sliced", "1 garlic clove - minced", "1/2 cup butternut squash - peeled and diced", "1/4 cup water", "1/2 cup cauliflower - diced", "1/4 cup firm tofu - patted dry and small diced", "2 mushrooms - sliced", "1 cup spinach - chopped", "1/4 cup tomato - diced", "1/2 Tbsp curry powder", "1/2 Tbsp turmeric powder", "1/2 tsp cumin powder", "1/2 tsp ginger - peeled and minced", "1/4 tsp chili flakes", "1/2 tsp lemon - zest", "salt to taste", "1 cup canned coconut milk", "1 1/2 cup rice - boiled and kept warm"], instructions: "In a large pot, saute the onions and the garlic in the oil over medium-high heat for 2 minutes. Add the butternut squash and the water. Cook on medium heat, until barely tender. Add the cauliflower and the tofu, cook for 1 minutes. Add the rest of the vegetables and cook for 2 minutes. Turn the heat to low, add the spices and lemon zest, mix until combined. Add salt to taste. Add the coconut milk and mix. Cook for 5 minutes, until everything is incorporated with the coconut milk and the curry is hot. Serve hot with rice.")
asian_quinoa_salad = Recipe.create(name: "Asian style quinoa salad", allergy_code: "GF, VE, NF", ingredient_list: ["3/4 cup quinoa", "1 cup water", "1/8 tsp salt", "1/2 cup firm tofu - patted dry and diced", "1/2 Tbsp sesame oil", "1/2 tsp GF soy sauce", "1/2 cup edamame - cooked and deshelled", "1/2 cup (no salt added) canned corn", "1/2 cup kale - chopped", "1/2 cup cabbage - shredded", "1/2 carrot - shredded", "1/4 cup cucumber - diced", "1/8 cup dried apricots - chopped", "1/8 cup GF soy sauce", "1/4 Tbsp sesame oil", "1/4 Tbsp vegetable oil", "1/2 Tbsp rice wine vinegar", "1 Tbsp scallions - chopped", "1/8 cup cilantro - chopped", "1/2 Tbsp sesame seeds", "1/8 tsp ginger - grated", "1/8 tsp chili flakes", "1/8 tsp salt"], instructions: "Preheat the oven to 425 degrees F. 
Cook the quinoa: rinse the quinoa. Place it in a pot with water and salt. Bring it to a boil, then lower the heat to low and cook for 10 minutes or until the liquid is absorbed. Set aside and let it chill down.
Bake the tofu: in a bowl mix the sesame oil and the GF soy sauce. Toss in the tofu. Place it on a baking tray lined with parchment paper in a single layer. Bake for 10 minutes. Set aside and let it chill down.
Assemble the salad: place all the other ingredients in a large bowl. Add the tofu and the quinoa. Mix well. 
Make the dressing: place all ingredients in a jar and shake well. 
Pour the dressing on the salad and toss well before serving.")
coconut_rice_bowl = Recipe.create(name: "Coconut rice bowl with spicy tomato salsa", allergy_code: "GF, VE, NF", ingredient_list: ["1 1/2 cup rice", "1/4 cut coconut flakes", "1 1/2 cup rice milk", "3/4 cup water", "1/2 tsp salt", "1 1/4 cup sweet potatoes - cut into wedges", "1 Tbsp vegetable oil", "1/4 tsp chipotle powder", "1/2 tsp dried basil", "1/4 tsp salt", "1 cup canned black beans", "1 bay leaf", "1/4 tsp salt", "1 Tbsp vegetable oil", "1 clove garlic - minced", "2 cup collard greens - chopped", "1/4 tsp salt", "1/4 tsp black pepper", "1/2 cup tomato - diced", "1/4 tsp chipotle powder", "1/4 tsp cayenne pepper powder", "1 Tbsp lime - juiced", "1/4 cup bell pepper - small diced", "1/4 tsp salt"], instructions: "Make the rice: place a pan on medium heat, add the coconut flakes. Toast, stirring often, until golden. In a pot, combine all the ingredients. Bring to a boil, then cook over medium/low heat until tender. Keep warm.
Make the sweet potatoes: turn on the oven to 400 degrees F. Combine all ingredients in a bowl and toss together to make sure spices are bound to the potatoes. Oil a half sheet pan, place potatoes on top making sure they don’t overlap. Bake until tender; about 10-15 minutes. Keep warm.
Make the beans: combine all ingredients in a pot, bring to a boil. Then let it simmer so the beans absorb the spices flavor. Keep warm.
Make the greens: in a skillet, warm up the oil on medium heat. Add the garlic, cook for 1 minute. Add the greens and sauté until tender. Keep warm.
Make the salsa: add all ingredients in a blender. Pulse until smooth. Adjust with salt. Set aside.
Serve all components at the same time to make your own rice bowl.")
roasted_broccoli_pasta = Recipe.create(name: "Roasted broccoli pasta", allergy_code: "VE, NF", ingredient_list: ["2 cup short pasta", "1 cup broccoli - florets chopped, stalks peeled and minced", "1 garlic clove - minced", "2 Tbsp olive oil", "1/4 tsp salt", "1/4 tsp chili flakes", "1/8 cup parsley - minced"], instructions: "In a large pot, bring water to a boil. Add the oil to a pan and warm it up over medium heat. Add the garlic and cook for 1 minute. Add the broccoli. Season with salt and chili flakes. Stir often until all ingredients are combined and the broccoli is browning but still firm. Add hot water if it tends to stick to the pan.
When the pasta water boils, add salt until it tastes like sea water. Add the pasta. Cook until al dente. Transfer 1 cup of pasta water to a bowl. Drain the pasta and transfer to the pan with the veggies. Sauté for a few minutes to incorporate the sauce flavors into the pasta, add more olive oil and some pasta water if needed.")
vegan_pozole = Recipe.create(name: "Vegan pozole", allergy_code: "GF, VE, NF", ingredient_list: ["1/2 dried ancho chile - slit open, seeds and veins removed", "1/8 cup vegetable oil", "1/2 cup onio - diced", "1 garlic clove - minced", "1 tsp apple cider vinegar", "1/2 tsp ground cumin", "1/4 tsp dried oregano", "1/8 tsp ground clove", "1/4 tsp sugar", "1/2 cup water", "1 cup (no salt added) canned hominy - drained", "1 cup (no salt added) canned kidney beans - drained", "1 cup zucchini - diced", "1 cup bell pepper - diced", "1/2 cup (no salt added) canned corn - drained", "1/8 cup jalapeño pepper - seeds and veins removed, sliced thin", "1/8 cup serrano pepper - seeds and veins removed, sliced thin", "2 1/2 cup water", "1/4 tsp salt", "1/4 tsp black pepper", "garnish: 1/2 cup avocado - sliced", "garnish: 1/4 cup cabbage - shredded", "garnish: 1/8 cup serrano pepper - sliced thin", "garnish: 1/4 cup onion - small diced", "garnish: 1/8 cup radish - sliced thin", "garnish: 2 lime wedges", "garnish: 1/2 cup GF tortilla chips"], instructions: "Heat a cast iron skillet over medium heat until hot. Open the ancho chiles flat, toast them in the hot skillet by pressing down with a spatula and turning on both sides. Toast them until fragrant and the insides change color, about 1 minute.
Transfer them to a bowl. Cover them with cold water and let them soak until soft, about 20 minutes.
In the meantime, warm up the oil in a large pot, add the onion and cook over medium heat, stirring occasionally, until golden. Add the garlic and cook for 2 more minutes. Remove from heat.
Drain the chiles and transfer them to a blender. Add the vinegar, the cumin, the oregano, the clove, the sugar, and the water. Blend until smooth, adjust with salt to taste.
Add the prepared chile purée to the pot and cook over low heat, stirring occasionally, for 5 minutes.
Add the hominy, the beans, the zucchini, the bell pepper, the corn, the jalapenos, the serranos, and the water. Bring to a boil. Simmer, partially covered and stirring occasionally until the veggies are tender. Add salt and pepper to taste.
Serve the vegan pozole hot with garnishes on the side.")
veggies_tagine = Recipe.create(name: "Vegetable tagine with couscous", allergy_code: "VE, NF", ingredient_list: ["1 1/2 cup water", "1/2 tsp salt", "1 cup couscous", "1/4 cup raisins", "1/4 tsp ginger - shredded", "1/4 tsp cardamom powder", "1/4 tsp nutmeg powder", "1/4 tsp cinnamon powder", "1/4 tsp turmeric powder", "1/4 tsp coriander seeds - ground", "1/4 tsp fennel seeds - ground", "1/4 tsp allspice powder", "1/4 tsp black pepper", "1/4 tsp white pepper", "1/4 tsp cayenne powder", "1/4 tsp ground clove", "2 Tbsp vegetable oil", "1 garlic clove - minced", "1/4 cup onion - minced", "1/2 cup potato - small diced", "1/2 cup carrot - diced", "1/4 cup bell pepper - small diced", "1/4 cup zucchini - diced", "1/2 cup (no salt added) canned chickpeas - drained", "1/4 cup olives - pitted", "1 tsp lemon - zest", "1/4 tsp salt", "2 cup vegetable broth", "1/2 Tbsp tomato paste", "1/2 Tbsp olive oil", "1/4 tsp salt"], instructions: "Make the couscous: boil the water and the salt. In a medium bowl, mix dry couscous and raisins. Pour water over the couscous mixture. Cover for 10 minutes. Once the liquid has been absorbed, fluff the couscous with a fork, cover it, and keep it warm.
Make the stew: Mix half the quantity for each spice together (reserve the rest for the spicy broth), set aside. In a large skillet, warm up the oil. Add the onion and the garlic, cook for 2 minutes on medium heat. Add the spices, mix until combined. Add the potato and cook for 2 minutes. Add the carrots, the zucchini, and the bell pepper, cook for 5 minutes adding just enough water to avoid it sticking to the pan. Add the chickpeas, the olives, the lemon zest, and the salt to taste. Mix well. Add the vegetable broth. Let it cook for 5 minutes. Adjust with salt. Keep warm.
Make the spicy broth: mix the rest of the spices. Add the garlic, the tomato paste, and the olive oil. Mix until combined. Bring the vegetable broth to a boil. Pour it over the spicy garlic mixture. Mix well and adjust with salt. Keep warm.
Serve each component separately so that each person can make their own bowl with couscous at the bottom, a ladle of stew and a few tablespoons of spicy broth on top.")
southwest_salad = Recipe.create(name: "Southwest salad", allergy_code: "GF, VE, NF", ingredient_list: ["1 Tbsp vegetable oil", "3/4 cup sweet potato - diced", "1 tsp chipotle powder", "1/4 tsp salt", "1 cup kale - chopped", "1 Tbsp lime - juiced", "1 cup lettuce - chopped", "1 cup (no salt added) canned black beans - drained", "1/2 cup (no salt added) canned corn - drained", "1 cup avocado - diced", "1/2 cup tomato - diced", "1/4 cup red onion - small diced", "1/8 cup rice milk", "1/8 cup silken tofu", "1/4 cup olive oil", "1/2 Tbsp lime - juiced", "1/8 cup cilantro - chopped", "1 garlic clove - chopped", "1/2 tsp cumin powder", "1/4 tsp salt", "garnish: 1/4 tsp black pepper", "garnish: 1/2 cup GF corn tortilla chips", "garnish: 2 lime wedges", "garnish: 1/8 cup cilantro - chopped"], instructions: "Preheat the oven to 450 degrees F. In a bowl, mix the chipotle powder, the salt and the sweet potatoes until well incorporated. Grease an oven pan with vegetable oil. Add the seasoned sweet potatoes in a single layer. Bake until barely tender, about 10 minutes. Let cool down.
Make the salad: massage the kale with lime juice to tenderize it. Add all the other ingredients (reserve a 1/4 cup of avocado for the dressing), mix well by hand. Add the cooled sweet potatoes. 
Make the dressing: put all the ingredients in a blender. Pulse until smooth. Adjust with salt and pepper to taste. Keep refrigerated until use.
Pour some dressing on the salad and toss well. Offer garnishes.")
vegan_mac_and_cheese = Recipe.create(name: "Vegan mac and cheese with veggies medley", allergy_code: "VE, NF", ingredient_list: ["2 Tbsp coconut oil or vegan butter - plus some for greasing the pan", "1 1/2 Tbsp flour", "1/2 cup rice milk", "1/8 tsp salt", "1/8 tsp black pepper", "1/8 tsp nutmeg powder", "1/2 Tbsp vegetable oil", "1 cup cauliflower - diced", "1/4 cup onion - diced", "2 cup macaroni elbow pasta - cooked al dente, then rinsed and drained", "1/4 cup panko bread crumbs", "1 Tbsp vegetable oil", "1 garlic clove - minced", "1 cup kale - chopped", "1/3 cup mushroom - sliced", "1/2 cup zucchini - diced", "1/3 cup carrot - sliced", "1/3 cup bell pepper - chopped", "1/4 tsp salt", "1/4 tsp black pepper"], instructions: "Make the vegan béchamel: in a medium pot melt the coconut oil over medium heat. Remove from the heat. Add the flour, whisk together. Add the milk slowly without stopping whisking until all is incorporated and there are no lumps. Put it back on low heat, keep whisking to avoid the formation of lumps. Remove from the heat when it starts getting dense. Add the nutmeg, and salt and pepper to taste. Keep aside. In a skillet, warm up the vegetable oil, add the onion and the cauliflower. Saute until golden brown. Place them in a blender and pulse until smooth. Add the mixture to the vegan bechamel. Adjust with salt and pepper to taste.
Bake the vegan mac and cheese: preheat the oven to 375 degrees F. Grease a baking pan with vegetable oil, add the pasta and vegan bechamel. Mix well and level evenly. Sprinkle the panko bread crumbs evenly on top. Bake for 15 minutes or until the top is golden.
Make the veggies medley: in a skillet, warm up the vegetable oil. Add the garlic and cook for 1 minute on medium heat. Add the vegetables and saute them until tender. Adjust with salt and pepper to taste. Serve hot alongside the vegan mac and cheese.")
falafel = Recipe.create(name: "Falafel with roasted peppers, hummus and cucumber-tomato salad", allergy_code: "GF, VE, NF", ingredient_list: ["1 bell pepper", "1 Tbsp olive oil", "1/8 tsp salt", "1 cup tomato - diced", "3/4 cup cucumber - diced", "1/8 cup red onion - small diced", "1/2 Tbsp dried dill", "1/8 cup parsley - minced", "1 Tbsp olive oil", "1 tsp red wine vinegar", "1/4 tsp salt", "3/4 cup (no salt added) canned chickpeas - drained", "2 Tbsp lemon - juiced", "2 Tbsp tahini", "1 garlic clove", "1 Tbsp olive oil", "1/4 tsp cumin powder", "1/4 tsp smoked paprika", "1 Tbsp water", "1/4 tsp salt", "1 cup (no salt added) canned chickpeas - drained", "1/2 cup parsley - minced", "1/8 cup onion - minced", "1 garlic clove - minced", "1/2 Tbsp cumin powder", "1/2 Tbsp coriander powder", "1/4 tsp chili flakes", "1/2 tsp baking soda", "1/2 tsp salt", "2 Tbsp cornstarch", "2 Tbsp vegetable oil"], instructions: "Make the peppers: turn the oven to 450 degrees F. Line an oven pan with parchment paper. Wash the peppers, brush them with oil, and place them on the tray. Bake until roasted, about 20-30 minutes. Remove them from the oven and place them in a sealed container for 10 minutes. Peel, deseed, and sprinkle them with salt. Set aside until ready to use.
Make the salad: combine tomatoes, cucumbers, red onion, dried dill, parsley, olive oil, red wine vinegar and salt in a salad bowl; toss well. Set aside in the cooler until ready to use. 
Make the hummus: in a food processor combine the lemon juice and the tahini. Pulse until creamy. Add the garlic, the olive oil, and the cumin. Pulse until combined. Add the water and the chickpeas. Pulse until smooth. Add salt to taste and mix well. Transfer to a bowl. Sprinkle the paprika on top. Cover and set aside in the cooler until ready to use.
Make the falafel: preheat the oven to 375 degrees F. Place the rest of the ingredients in a food processor. Pulse until the mixture is coarse like sand. Transfer to a bowl and place in the cooler for 20 minutes. After 20 minutes, take the falafel mixture out of the cooler and form golf size balls (one per person) with your hands. Cover baking trays with parchment paper and grease them. Place the falafel balls on the trays, press on them to flatten them a bit, spray them with vegetable oil. Bake for 15 minutes on one side, then flip them and bake them for another 10-15 minutes, or until golden. 
Serve the falafel warm with roasted peppers, hummus, and cucumber-tomato salad as sides.")
vegan_paella = Recipe.create(name: "Vegan paella", allergy_code: "GF, VE, NF", ingredient_list: ["1 Tbsp sunflower oil", "1/4 cup onion - diced", "1 garlic clove - minced", "1/4 cup zucchini - diced", "1/4 cup bell pepper - diced", "1/2 cup tomato - diced", "1 bay leaf", "1/8 tsp chili flakes", "1/2 tsp smoked paprika", "1 tsp paella spice blend", "1/8 cup parsley - minced", "1 cup short grain rice", "3 1/2 cup vegetable broth", "1/2 cup (no salt added) canned chickpeas - drained", "1/8 cup olives - chopped", "1/4 cup peas", "1/2 tsp salt", "garnish: 2 lemon wedges"], instructions: "In a large non-stick pot, warm up the vegetable oil over medium-high heat. Add the onion and the garlic, cook for 1 minute. Add the veggies, the spices, and the parsley, and cook for about 5 minutes. Adjust with salt. Add the rice and the broth. Gently move the vegetables around so that the rice falls at the bottom of the pot. Cook uncovered at low temperature (maintaining a gentle boil) for 10 minutes. Add the chickpeas, the peas, and the olives. Mix well. Cook for 10 more minutes, rotating the pot often to ensure uniform cooking. If the liquids seem to cook off too quickly, add a little extra broth to avoid the rice sticking to the bottom of the pan. 
Taste the rice to ensure it is al dente and adjust with salt if needed. Turn off the heat, cover the pot. Let it sit for about 10 minutes so that the rice absorbs all the remaining liquids. Serve with lemon wedges.")
minestrone = Recipe.create(name: "Minestrone", allergy_code: "GF, VE, NF", ingredient_list: ["1 1/2 Tbsp sunflower oil", "1/4 cup onion - diced", "1/2 cup carrot - diced", "1/2 cup celery - diced", "1 garlic clove - minced", "2 cup vegetable broth", "1/2 cup potato - diced", "1/2 cup zucchini - diced", "1 cup kale - chopped", "1 cup (no salt added) canned tomatoes", "1/2 tsp dried oregano", "1/2 tsp dried dill", "1/2 tsp fennel seeds", "1/2 tsp dried thyme", "1 cup (no salt added) canned cannellini beans - drained", "1/8 cup short grain rice", "1/2 tsp salt", "1/2 tsp black pepper", "1/4 cup basil - minced", "1/4 cup parsley - minced"], instructions: "In a large pot, warm up the oil. Add the onion, the carrot, the celery and the garlic. Cook for 5 minutes. Add water if the vegetables tend to stick to the bottom of the pot. Add the vegetable broth and all the vegetables but the cannellini beans. Cook for 30 minutes on medium-low. Add the dried herbs. Add the cannellini beans and the rice and cook for another 15 minutes, or until the rice is cooked. Add salt and pepper to taste. Add the basil and the parsley and mix well. Serve hot.")
roasted_veggie_pasta = Recipe.create(name: "Roasted veggie pasta with creamy cauliflower sauce", allergy_code: "VE, NF", ingredient_list: ["1/4 cup eggplant - small diced", "1/4 cup bell pepper - small diced", "1/2 cup tomato - small diced", "1/4 cup zucchini - small diced", "3 Tbsp olive oil", "1/4 tsp salt", "1/4 tsp black pepper", "1 cup cauliflower - cut into large pieces", "1/8 cup rice milk", "1/8 tsp nutmeg powder", "2 cup short pasta", "1 garlic clove - minced", "1/8 cup parsley - minced", "1/8 cup basil - minced"], instructions: "Preheat the oven to 400 degrees F. Place the eggplant, the bell pepper, the tomatoes, and the zucchini in a large bowl. Drizzle with half of the olive oil, salt and pepper. Mix until all the vegetables are coated with oil and spices. Place the vegetables on an oven pan. Roast in the oven until tender; about 10 minutes.
In a medium pot, cover the cauliflower with water, bring to a boil and cook until tender. Drain it and place it in a blender. Pulse until completely blended and smooth. Add the rice milk and the nutmeg, and pulse some more until it reaches a creamy consistency. Adjust with salt and pepper to taste. Mix well and keep warm.
Cook the pasta until al dente. In a large pan, warm up the remaining oil over low heat. Add the garlic and cook for 1 minutes. Remove the veggies from the oven and add them to the pan. Toss in the pasta. Add the parsley and the basil. Mix well. Add the cauliflower sauce, mix well and adjust with salt and pepper if needed. Saute for 2 minutes and serve.")
tex_mex_casserole = Recipe.create(name: "Suzie's Tex-Mex casserole", allergy_code: "VE, NF", ingredient_list: ["1 Tbsp vegetable oil", "1/4 cup onion - small diced", "1 garlic clove - minced", "1/8 cup jalapeño - deseeded, veins removed, thinly sliced", "1/2 cup bell pepper - diced", "1/4 tsp smoked paprika", "1/8 tsp cayenne pepper powder", "1 tsp taco seasoning", "1/2 cup (no salt added) canned corn - drained", "1/2 cup (no salt added) canned black beans - drained", "1/2 cup canned fire roasted tomatoes", "1/4 tsp salt", "3/4 cup cornmeal", "3/4 cup flour", "1/2 Tbsp baking powder", "1/2 tsp baking soda", "1/2 tsp salt", "1/3 cup sugar", "1 cup plant-based milk", "3/4 tsp apple cider vinegar", "1/4 cup vegetable oil"], instructions: "Preheat the oven to 350 degrees F. Use 1 Tbsp vegetable oil to grease an 8x2 inch loaf pan.
In a large pot, warm up the remaining vegetable oil. Add the onion and the garlic, cook over low-medium heat for 5 minutes. Add the jalapeno and the bell pepper. Cook for 2 minutes. Add the spices, the corn, the beans, and the tomatoes. Adjust with salt to taste, cook for 5 minutes.
Transfer the mixture to the greased pan.
Make the cornbread batter: mix all the dry ingredients together and set aside. Mix the wet ingredients. Pour the wet ingredients into the dry ingredients and mix until just combined. 
Pour the batter over the veggies mixture. Bake in the oven for 30-40 minutes or until the cornbread is golden. 
Serve hot.")
potato_leek_soup = Recipe.create(name: "Potato and leeks soup with garlic bread", allergy_code: "VE, NF", ingredient_list: ["1 Tbsp sunflower oil", "1 1/4 cup leek - chopped", "1/4 cup onion - diced", "1 1/2 cup potato - diced", "2 cup vegetable broth", "1 bay leaf", "1/2 tsp dried marjoram", "1/2 tsp dried thyme", "1/4 tsp salt", "1/4 tsp black pepper", "1/8 cup parsley - chopped", "1/4 baguette bread", "1/8 cup olive oil", "1 garlic clove - minced", "1/2 Tbsp parsley - chopped", "1/8 tsp salt"], instructions: "Make the soup: warm up the oil in a large pot. Add the leeks and the onion. Cover and cook over low heat until tender. Add some water to keep it from burning. Add the potatoes, the vegetable broth, the bay leaf,  the marjoram, the thyme and salt and pepper. Cook until the potatoes are tender, about 20 minutes. Adjust with salt. Remove the bay leaf from the soup. Use an immersion blender to blend about half of the soup to obtain a chunky but creamy soup. Garnish with parsley. 
Make the garlic bread: turn on the oven to 350 degrees F. In a bowl, mix the oil, the garlic, and the parsley until creamy. Cut the baguettes in half, horizontally. Spread the oil mixture on the bread with a brush. Bake for about 10 minutes, then move the pan under the broiler for 1 minute. Cut into 1-inch slices, serve warm with the soup.")
veggies_stir_fry = Recipe.create(name: "Veggies stir fry with rice noodles", allergy_code: "GF, VE, NF", ingredient_list: ["1/4 Tbsp sesame oil", "1/4 cup vegetable broth", "1 tsp sugar", "1 1/2 Tbsp GF soy sauce", "1 1/2 Tbsp vegetable oil", "1 garlic clove - minced", "1/2 Tbsp ginger - minced", "1/8 cup scallion - minced", "1/8 cup jalapeño pepper - deseeded and sliced thin", "1/2 cup green beans - chopped", "1/4 cup carrot - julienned", "1/2 cup broccoli - diced", "1/4 cup (no salt added) canned corn - drained", "1/4 tsp chili flakes", "6 oz rice noodles", "garnish: 2 lime wedges", "1/8 cup cilantro - minced"], instructions: "Make the sesame sauce: in a bowl, mix the sesame oil, the broth, the sugar, and the GF soy sauce together and set aside.
In a large skillet, warm up the sunflower oil on medium heat. Add the garlic, the ginger, the scallions, and the jalapeno and cook for 1 minute. Add the vegetables, stirring often, until they become slightly brown. Add the sesame sauce and cook for 1 minute. Sprinkle with red chili flakes. Set aside and keep warm.
Bring a large pot of water to boil. Stir in the noodles. Cook according to package directions (usually 2 minutes). Drain well. Rinse the noodles well and drain them to keep them from sticking together. Spray them with vegetable oil and mix well. Serve the noodles on the side of the veggies stir fry. Offer lime wedges and cilantro as garnishes.")
roasted_squash_chili = Recipe.create(name: "Roasted squash chili", allergy_code: "VE, NF", ingredient_list: ["3/4 cup cornmeal", "3/4 cup flour", "1/2 Tbsp baking powder", "1/2 tsp baking soda", "1/2 tsp salt", "1/3 cup sugar", "1 cup rice milk", "3/4 tsp apple cider vinegar", "1/4 cup sunflower oil", "3 Tbsp sunflower oil", "1 1/4 cup butternut squash - peeled and diced", "1/2 cup onion - small diced", "1 garlic clove - minced", "1/2 cup bell pepper - diced", "1/2 Tbsp chipotle powder", "1/4 tsp cayenne powder", "1 tsp cumin powder", "1/2 tsp salt", "1 cup (no salt added) canned black beans", "1 cup (no salt added) canned diced tomatoes", "garnish: 1/8 cup cilantro - chopped", "garnish: 2 lime wedges"], instructions: "Make the cornbread: preheat the oven to 350 degrees F. Grease an 8x2 inch loaf pan with oil. Mix all the dry ingredients (from cornmeal to sugar) together and set aside. Mix the wet ingredients (from rice milk to 1/4 cup sunflower oil). Pour the wet ingredients into the dry ingredients and mix until just combined. Pour the mixture into the oven pan. Bake for about 45 minutes, or until a toothpick inserted into the center comes out clean. Let it cool completely before cutting into squares. 
Make the chili: preheat the oven to 450 degrees F. Grease a sheet pan with oil. Place the squash on the pan on a single layer. Sprinkle it with salt. Bake it for 20 minutes or until just tender.
In a large pot, warm up the remaining oil. Add the onion and the garlic. Cook for 5 minutes on medium heat. Add the green bell pepper. Cook for 1 minute. Add the spices and salt to taste and mix well. Add the beans (with their water) and the tomatoes. Adjust with salt. Cook for 10 minutes on low heat. Add the roasted squash and mix well. Cook for 2 minutes, until all the ingredients are well incorporated. 
Serve hot alongside cornbread, cilantro, and lime wedges.")
vegan_burger = Recipe.create(name: "", allergy_code: "", ingredient_list: [], instructions: "")
taco_bar = Recipe.create(name: "", allergy_code: "", ingredient_list: [], instructions: "")
pesto_pasta = Recipe.create(name: "", allergy_code: "", ingredient_list: [], instructions: "")
tofu_pad_thai = Recipe.create(name: "", allergy_code: "", ingredient_list: [], instructions: "")
mediterranean_rice_salad = Recipe.create(name: "", allergy_code: "", ingredient_list: [], instructions: "")
lentil_and_veggie_soup = Recipe.create(name: "", allergy_code: "", ingredient_list: [], instructions: "")
veggies_pizza = Recipe.create(name: "", allergy_code: "", ingredient_list: [], instructions: "")
mediterranean_salad = Recipe.create(name: "Mediterranean salad", allergy_code: "GF, VE, NF", ingredient_list: ["1 1/2 cup lettuce - chopped", "1/2 cup tomatoes - small diced", "1/8 cup olives - pitted and chopped", "1/4 cup cucumber - small diced", "1 Tbsp mint - chopped", "1 1/2 Tbsp olive oil", "1/2 Tbsp red wine vinegar", "1/4 tsp salt", "1/4 tsp black pepper"], instructions: "In a large bowl, combine all veggies. In a jar combine the mint, the olive oil, the vinegar, the salt and the pepper and shake well. Pur the dressing on the salad and toss well.")

puts "Seeding ingredients..."
# lettuce = Ingredient.create(name: "lettuce")
# tomato = Ingredient.create(name: "tomato")

broccoli = Ingredient.create(name: "broccoli")
carrot = Ingredient.create(name: "carrot")
asparagus = Ingredient.create(name: "asparagus")
garlic = Ingredient.create(name: "garlic")
celery = Ingredient.create(name: "celery")
tomato = Ingredient.create(name: "tomato")
olive = Ingredient.create(name: "olive")
cucumber = Ingredient.create(name: "cucumber")
avocado = Ingredient.create(name: "avocado")
eggplant = Ingredient.create(name: "eggplant")
jalapeño = Ingredient.create(name:"jalapeño pepper")
bell_pepper = Ingredient.create(name: "bell pepper")
serrano = Ingredient.create(name: "serrano pepper")
parsley = Ingredient.create(name: "parsley")
mint = Ingredient.create(name: "mint")
cilantro = Ingredient.create(name: "cilantro")
scallion = Ingredient.create(name: "scallion")
basil = Ingredient.create(name: "basil")
kale = Ingredient.create(name: "kale")
lettuce = Ingredient.create(name: "lettuce")
spinach = Ingredient.create(name: "spinach")
collard = Ingredient.create(name: "collard")
lime = Ingredient.create(name: "lime")
lemon = Ingredient.create(name: "lemon")
onion = Ingredient.create(name: "onion")
red_onion = Ingredient.create(name: "red onion")
potato = Ingredient.create(name: "potato")
sweet_potato = Ingredient.create(name: "sweet potato")
zucchini = Ingredient.create(name: "zucchini")
mushroom = Ingredient.create(name: "mushroom")
green_bean = Ingredient.create(name: "green bean")
butternut_squash = Ingredient.create(name: "butternut squash")
cauliflower = Ingredient.create(name: "cauliflower")
tofu = Ingredient.create(name: "tofu")
edamame = Ingredient.create(name: "edamame")
cabbage = Ingredient.create(name: "cabbage")
ginger = Ingredient.create(name: "ginger")
radish = Ingredient.create(name: "radish")
leek = Ingredient.create(name: "leek")
corn = Ingredient.create(name: "corn on the cob")
bean_sprout = Ingredient.create(name: "bean sprout")

puts "Connecting recipes and ingredients..."
# blt.ingredients << [tomato, lettuce]
# salad.ingredients << [lettuce]


puts "Done seeding!"